# HOW TO USE:
# 1. Create the environment
#    conda env create -f environment.yml
# 2. Activate the environment
#    conda activate sd2
# 3. Updating in the future
#    If there are new pacakges added to the requirements.txt or changes in the environment.yml
#    you don't need to delete and recreate the environment. You can update it with:
#    conda env update -f environment.yml --prune

name: sd2
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python (Adjust version if needed. Django 5.2+ requires 3.10+)
  - python=3.11
  - pip

  # ----- Local Development & Data Science Tools -----
  # Installing these via Conda avoids messy local binary issues
  - jupyter
  - pandas=2.3.3
  - numpy=2.2.6
  - matplotlib=3.10.8
  - psutil
  - colorama
  # - pywin32  # Uncomment if you are developing on Windows

  # ----- Core Project Dependencies -----
  # This tells Conda to use pip to install the rest of your Heroku packages
  - pip:
      - -r requirements.txt