"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv, find_dotenv

# Load environment variables from .env file (only affects local dev;
# on Heroku, env vars are set via Config Vars)
load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Environment Detection
# Set DJANGO_ENVIRONMENT to: local | integration | staging | production
# ---------------------------------------------------------------------------
ENVIRONMENT = os.environ.get('DJANGO_ENVIRONMENT', 'local')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if ENVIRONMENT == 'local':
        SECRET_KEY = 'django-insecure-local-dev-key-CHANGE-ME-in-production'
    else:
        raise ValueError('SECRET_KEY environment variable is required in non-local environments.')

SALT_KEY = os.environ.get('SALT_KEY', 'local-dev-salt-key-CHANGE-ME')

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

FIELD_ENCRYPTION_KEYS = [
    'f164h6a7591d3d540a946c6e0d2344ef9ae1951cddf3241430edc4273954513a', # Example 32-byte hex key
]

# Comma-separated list of allowed hosts, e.g. "myapp.herokuapp.com,mydomain.com"
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Always allow Heroku subdomains in non-local environments
if ENVIRONMENT != 'local' and '.herokuapp.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.herokuapp.com')

# ------------------------------------------
# Django Q2 (Background Worker) Settings
# ------------------------------------------

Q_CLUSTER = {
    'name': 'logodiscover_cluster',
    'orm': 'default',  
    
    # WORKER CONFIGURATION
    'workers': 4,       # Number of concurrent worker processes. 4 is a safe default for a Standard Heroku Dyno.
    'recycle': 500,     # Restarts a worker after it processes 500 tasks to prevent memory leaks.
    'timeout': 300,     # Max time (in seconds) a task is allowed to run before being killed. 
    'retry': 360,       # Set to 5 minutes (300s) here, but adjust if Gemini AI generation takes longer
    
    # DATABASE MANAGEMENT
    'compress': True,   # Compresses task data in the DB to save storage space.
    'save_limit': 250,  # Only keeps the history of the last 250 successful tasks in the DB to prevent bloat.
    
    # QUEUE BEHAVIOR
    'queue_limit': 500, # Max number of tasks that can be queued in memory at once.
    'catch_up': False,  # If your worker goes offline, don't execute missed scheduled tasks all at once when it boots back up.
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
	'debug_toolbar',
    'accounts',
    'api',
    'rest_framework',
    'django_q'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# On Heroku, DATABASE_URL is set automatically by the Heroku Postgres add-on.
# Locally, falls back to the default local PostgreSQL connection.

DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD', '')

_DEFAULT_DB_URL = (
    f"postgres://postgres:{DATABASE_PASSWORD}@localhost:5432/postgres"
    if DATABASE_PASSWORD
    else 'postgres://postgres@localhost:5432/postgres'
)

DATABASES = {
    'default': dj_database_url.config(
        default=_DEFAULT_DB_URL,
        conn_max_age=600,
        ssl_require=(ENVIRONMENT not in ('local', 'test')),
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'api.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'

# Whitenoise compressed & hashed static files
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    '127.0.0.1'
]


LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
TESTING = 'test' in sys.argv or 'PYTEST_VERSION' in os.environ

if not TESTING and ENVIRONMENT == 'local':
    INSTALLED_APPS = [
        *INSTALLED_APPS,
        'debug_toolbar'
    ]
    MIDDLEWARE = [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        *MIDDLEWARE
    ]

# ---------------------------------------------------------------------------
# Security settings — enabled for staging & production
# ---------------------------------------------------------------------------
if ENVIRONMENT in ('staging', 'production'):
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ---------------------------------------------------------------------------
# Logging — basic config that works on Heroku (stdout)
# ---------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if ENVIRONMENT != 'local' else 'DEBUG',
    },
}