"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv, find_dotenv

# Load environment variables from .env file (only affects local dev;
# on Heroku, env vars are set via Config Vars)
load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# URL prefix for static files
STATIC_URL = 'static/'

# Tell Django where to find global static files
STATICFILES_DIRS = [
    BASE_DIR / "static", 
]

# ---------------------------------------------------------------------------
# Environment Detection
# Set DJANGO_ENVIRONMENT to: local | integration | staging | production
# ---------------------------------------------------------------------------
ENVIRONMENT = os.environ.get('DJANGO_ENVIRONMENT', 'local')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if ENVIRONMENT == 'local':
        SECRET_KEY = 'django-insecure-local-dev-key-CHANGE-ME-in-production'
    else:
        raise ValueError('SECRET_KEY environment variable is required in non-local environments.')

API_KEY = os.environ.get('GEMINI_API_KEY', 'local-gemini-api-key-CHANGE-ME')

SALT_KEY = os.environ.get('SALT_KEY', 'local-dev-salt-key-CHANGE-ME')

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

FIELD_ENCRYPTION_KEYS = [
    'f164h6a7591d3d540a946c6e0d2344ef9ae1951cddf3241430edc4273954513a', # Example 32-byte hex key
]

FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY')
if not FIELD_ENCRYPTION_KEY and ENVIRONMENT != 'local':
    raise ValueError('FIELD_ENCRYPTION_KEY environment variable is required in non-local environments.')

# Comma-separated list of allowed hosts, e.g. "myapp.herokuapp.com,mydomain.com"
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Allow LAN access during local VM testing
# Remove or replace with env var before pushing to production
_LAN_IP = os.environ.get('LAN_IP', '')
if _LAN_IP and _LAN_IP not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_LAN_IP)
# Always allow Heroku subdomains in non-local environments
if ENVIRONMENT != 'local' and '.herokuapp.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.herokuapp.com')

# Application definition

# ------------------------------------------
# Django Q2 (Background Worker) Settings
# ------------------------------------------

ASYNC_EMAIL_ENABLED = os.environ.get(
    'ASYNC_EMAIL_ENABLED',
    'true' if ENVIRONMENT != 'local' else 'false',
).lower() in ('true', '1', 'yes')

Q_CLUSTER = {
    'name': 'logodiscover_cluster',
    'orm': 'default',  
    
    # WORKER CONFIGURATION
    'workers': 4,       # Number of concurrent worker processes. 4 is a safe default for a Standard Heroku Dyno.
    'recycle': 500,     # Restarts a worker after it processes 500 tasks to prevent memory leaks.
    'timeout': 300,     # Max time (in seconds) a task is allowed to run before being killed. 
    'retry': 600,       # Set to 10 minutes (600s) here, but adjust if Gemini AI generation takes longer
    
    # DATABASE MANAGEMENT
    'compress': True,   # Compresses task data in the DB to save storage space.
    'save_limit': 250,  # Only keeps the history of the last 250 successful tasks in the DB to prevent bloat.
    
    # QUEUE BEHAVIOR
    'queue_limit': 500, # Max number of tasks that can be queued in memory at once.
    'catch_up': False,  # If your worker goes offline, don't execute missed scheduled tasks all at once when it boots back up.
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_q',
    'accounts',
    'api',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# On Heroku, DATABASE_URL is set automatically by the Heroku Postgres add-on.
# Locally, falls back to the default local PostgreSQL connection.

DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD', '')

_DEFAULT_DB_URL = (
    f"postgres://postgres:{DATABASE_PASSWORD}@localhost:5432/postgres"
    if DATABASE_PASSWORD
    else 'postgres://postgres@localhost:5432/postgres'
)

DATABASES = {
    'default': dj_database_url.config(
        default=_DEFAULT_DB_URL,
        conn_max_age=600,
        ssl_require=(ENVIRONMENT not in ('local', 'test')),
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'api.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Whitenoise compressed & hashed static files
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

'''
# For local development, use plain static file storage without manifest to avoid issues with missing files after collectstatic
# In production, use WhiteNoise's CompressedManifestStaticFilesStorage for better performance and cache busting.
# Staticfiles storage:
# - DEBUG/local development: plain storage (no manifest required)
# - non-DEBUG environments: hashed manifest storage via WhiteNoise
if DEBUG:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
'''

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    '127.0.0.1'
]

LOGIN_REDIRECT_URL = 'login_redirect'
LOGOUT_REDIRECT_URL = "home"

GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '').strip()
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET")
GOOGLE_OAUTH_ENABLED = bool(GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET)
# Set to False (or comment out this line and hardcode False) to skip the OTP modal after Google login.
GOOGLE_OAUTH_REQUIRE_OTP = os.environ.get('GOOGLE_OAUTH_REQUIRE_OTP', 'False').lower() in ('true', '1', 'yes')

# ---------------------------------------------------------------------------
# Email Configuration
# ---------------------------------------------------------------------------
EMAIL_BACKEND_TYPE = os.environ.get('EMAIL_BACKEND_TYPE', 'console')

# Determine if we're on Heroku
IS_HEROKU = 'DYNO' in os.environ or 'HEROKU' in os.environ
ADMIN_EMAIL_INBOX = os.environ.get('ADMIN_EMAIL_INBOX', 'cyberassessmenttool@gmail.com')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@localhost')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_BACKEND_TYPE == 'sendgrid' or IS_HEROKU:
    # Use SendGrid on Heroku
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.sendgrid.net')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', EMAIL_HOST_USER)
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', EMAIL_HOST_PASSWORD)
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', DEFAULT_FROM_EMAIL)
elif EMAIL_BACKEND_TYPE == 'smtp':
    # Use Gmail or other SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.sendgrid.net') # Defaults to SendGrid SMTP
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', EMAIL_HOST_USER)
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', EMAIL_HOST_PASSWORD)
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or DEFAULT_FROM_EMAIL)
else:
    # Development - console backend
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

TESTING = 'test' in sys.argv or 'PYTEST_VERSION' in os.environ

# ---------------------------------------------------------------------------
# Security settings — enabled for staging & production
# ---------------------------------------------------------------------------
if ENVIRONMENT in ('staging', 'production'):
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ---------------------------------------------------------------------------
# Logging — basic config that works on Heroku (stdout)
# ---------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if ENVIRONMENT != 'local' else 'DEBUG',
    },
}