# Generated by Django 5.2.6 on 2026-04-09 04:59

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', encrypted_fields.fields.EncryptedCharField(max_length=300)),
                ('email_domain', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('website_domain', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('external_ip', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('require_mfa_email', models.BooleanField(blank=True, default=False, null=True)),
                ('require_mfa_computer', models.BooleanField(blank=True, default=False, null=True)),
                ('require_mfa_sensitive_data', models.BooleanField(blank=True, default=False, null=True)),
                ('employee_acceptable_use_policy', models.BooleanField(blank=True, default=False, null=True)),
                ('training_new_employees', models.BooleanField(blank=True, default=False, null=True)),
                ('training_once_per_year', models.BooleanField(blank=True, default=False, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('questionnaire_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('auto_frequency', models.CharField(choices=[('n', 'None'), ('m', 'Monthly'), ('q', 'Quarterly'), ('y', 'Yearly')], max_length=1)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=api.models.User.profile_image_path)),
                ('color', models.CharField(choices=[('d', 'Dark'), ('l', 'Light')], default='d', max_length=1)),
                ('font_size', models.CharField(choices=[('l', 'Large'), ('m', 'Medium'), ('s', 'Small')], default='m', max_length=1)),
                ('email_inbox', encrypted_fields.fields.EncryptedEmailField(blank=True, max_length=254, null=True)),
                ('email', encrypted_fields.fields.EncryptedEmailField(max_length=254)),
                ('email_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('password', encrypted_fields.fields.EncryptedCharField(max_length=128)),
                ('first_name', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('last_name', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to (e.g., Executive, Manager, Technician, etc.)', related_name='api_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user (for exceptions).', related_name='api_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'permissions': [('can_invite', 'Can invite users to the organization.'), ('can_edit_permissions', "Can edit users' permissions in the organization.")],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', encrypted_fields.fields.EncryptedEmailField(max_length=254)),
                ('recipient_email_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='sent', max_length=20)),
                ('recipient_role', models.CharField(choices=[('org_admin', 'Org Admin'), ('observer', 'Observer'), ('tester', 'Tester')], default='observer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('invitation', 'Invitation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=api.models.get_otp_expiration)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'otp_code', 'purpose'], name='api_otpveri_email_7e6940_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=300)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('report_text', encrypted_fields.fields.EncryptedJSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_any_report', 'Can review any report, regardless of organization.'), ('can_generate_report', 'Can generate a new report.'), ('can_export_report', 'Can export report data.')],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_name', models.CharField(max_length=500)),
                ('overview', encrypted_fields.fields.EncryptedTextField()),
                ('recommendations', encrypted_fields.fields.EncryptedJSONField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Informational')])),
                ('affected_elements', encrypted_fields.fields.EncryptedTextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
            options={
                'permissions': [('can_view_risk', 'Can view the risk.'), ('can_view_all_risk', 'Can view any risk, regardless of organization.'), ('can_resolve_risk', 'Can resolve the risk and set as archived.'), ('can_generate_risk', 'Can generate new risks.')],
            },
        ),
        migrations.CreateModel(
            name='ScanToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_tokens', to='api.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Token',
                'verbose_name_plural': 'Scan Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('RECEIVED', 'Results Received'), ('GENERATING', 'Generating Report'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('report_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('target_subnet', encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted. The subnet that was scanned (e.g. 192.168.1.0/24).', null=True)),
                ('scanner_version', models.CharField(blank=True, max_length=20, null=True)),
                ('groups_completed', models.PositiveSmallIntegerField(default=0)),
                ('skipped_tools', models.JSONField(blank=True, default=list)),
                ('raw_findings_json', encrypted_fields.fields.EncryptedJSONField(blank=True, help_text='Encrypted. Full JSON findings from the exe. Deleted after report generation.', null=True)),
                ('finding_count_critical', models.PositiveSmallIntegerField(default=0)),
                ('finding_count_high', models.PositiveSmallIntegerField(default=0)),
                ('finding_count_medium', models.PositiveSmallIntegerField(default=0)),
                ('finding_count_low', models.PositiveSmallIntegerField(default=0)),
                ('finding_count_info', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.organization')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan', to='api.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan', to='api.scantoken')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
