# Generated by Django 5.2.6 on 2026-02-27 20:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', encrypted_fields.fields.EncryptedCharField(max_length=300)),
                ('email_domain', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('website_domain', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('external_ip', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('require_mfa_email', models.BooleanField(default=False)),
                ('require_mfa_computer', models.BooleanField(default=False)),
                ('require_mfa_sensitive_data', models.BooleanField(default=False)),
                ('employee_acceptable_use_policy', models.BooleanField(default=False)),
                ('training_new_employees', models.BooleanField(default=False)),
                ('training_once_per_year', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('auto_frequency', models.CharField(choices=[('n', 'None'), ('m', 'Monthly'), ('q', 'Quarterly'), ('y', 'Yearly')], max_length=1)),
                ('profile_img', models.ImageField(upload_to='')),
                ('color', models.CharField(choices=[('d', 'Dark'), ('l', 'Light')], default='d', max_length=1)),
                ('font_size', models.CharField(choices=[('l', 'Large'), ('m', 'Medium'), ('s', 'Small')], default='m', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to (e.g., Executive, Manager, Technician, etc.)', related_name='api_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user (for exceptions).', related_name='api_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'permissions': [('can_invite', 'Can invite users to the organization.'), ('can_edit_permissions', "Can edit users' permissions in the organization.")],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=300)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('report_text', encrypted_fields.fields.EncryptedJSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_any_report', 'Can review any report, regardless of organization.'), ('can_generate_report', 'Can generate a new report.'), ('can_export_report', 'Can export report data.')],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_name', models.CharField(max_length=500)),
                ('overview', encrypted_fields.fields.EncryptedTextField()),
                ('recommendations', encrypted_fields.fields.EncryptedJSONField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Informational')])),
                ('affected_elements', encrypted_fields.fields.EncryptedTextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
            options={
                'permissions': [('can_view_risk', 'Can view the risk.'), ('can_view_all_risk', 'Can view any risk, regardless of organization.'), ('can_resolve_risk', 'Can resolve the risk and set as archived.'), ('can_generate_risk', 'Can generate new risks.')],
            },
        ),
    ]
