# Generated by Django 5.2.6 on 2026-04-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_types_run',
            field=models.JSONField(blank=True, default=list, help_text='Which scan types were run: [tcp, udp, email, infra] as 1/0 flags.'),
        ),
    ]
