# Generated by Django
from django.db import migrations
from django.contrib.auth.management import create_permissions

def create_groups_and_permissions(apps, schema_editor):
    # 1. Force Django to create all permissions in the database right now
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    # 2. Get the models
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # 3. Create the Groups (This is what went missing!)
    admin_group, _ = Group.objects.get_or_create(name='Organization Admin')
    observer_group, _ = Group.objects.get_or_create(name='Observer')
    tester_group, _ = Group.objects.get_or_create(name='Tester')

    # 4. Define the permission codenames for each group
    observer_perms = [
        'view_report', 
        'view_risk',
    ]
    
    tester_perms = [
        'view_report',
        'view_risk',
        'can_resolve_risk',
    ]

    admin_perms = [
        'can_invite',
        'can_edit_permissions',
        'can_generate_report',
        'can_generate_risk',
        'view_report',
        'view_risk',
    ]

    # 5. Helper function to assign permissions to a group
    def assign_permissions(group, codenames):
        for codename in codenames:
            try:
                # Fetch the permission object from the database
                perm = Permission.objects.get(codename=codename)
                group.permissions.add(perm)
            except Permission.DoesNotExist:
                print(f"Warning: Permission '{codename}' not found.")

    # 6. Apply the permissions
    assign_permissions(observer_group, observer_perms)
    assign_permissions(tester_group, tester_perms)
    assign_permissions(admin_group, admin_perms)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]