# Generated by Django 5.2.6 on 2026-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('can_view_any_report', 'Can review any report, regardless of organization.'), ('can_generate_report', 'Can generate a new report.'), ('can_export_report', 'Can export report data.')]},
        ),
        migrations.RenameField(
            model_name='risk',
            old_name='affected',
            new_name='affected_elements',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_checked',
        ),
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='risk',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Informational')]),
        ),
    ]
