# Generated by Django 5.2.6 on 2026-03-31 17:32

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_inbox',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
