# Generated by Django 5.2.6 on 2026-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='recipient_role',
            field=models.CharField(choices=[('Org Admin', 'Organization Admin'), ('Tester', 'Tester'), ('Observer', 'Observer')], default='Observer'),
        ),
    ]
