# Generated by Django 5.2.6 on 2026-03-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='recipient_email_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
