# Generated by Django 5.2.6 on 2026-03-15 01:18

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('org_admin', 'Org Admin'), ('observer', 'Observer'), ('tester', 'Tester')], default='observer', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 3, 22, 1, 17, 50, 470120, tzinfo=datetime.timezone.utc))),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('has_security_policy', models.BooleanField(default=False)),
                ('conducts_regular_audits', models.BooleanField(default=False)),
                ('has_incident_response', models.BooleanField(default=False)),
                ('uses_encryption', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('invitation', 'Invitation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 3, 15, 1, 22, 50, 470120, tzinfo=datetime.timezone.utc))),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'otp_code', 'purpose'], name='api_otpveri_email_7e6940_idx')],
            },
        ),
    ]
