# Generated by Django 5.2.6 on 2026-03-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_role',
        ),
    ]
