# Generated by Django 5.2.6 on 2026-02-25 18:15

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email_domain',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='external_ip',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_domain',
            field=encrypted_fields.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=encrypted_fields.fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='risk',
            name='affected_elements',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='overview',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='recommendations',
            field=encrypted_fields.fields.EncryptedJSONField(),
        ),
    ]
