# Generated by Django 5.2.6 on 2026-03-31 13:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='user',
            name='organization_role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('org admin', 'Organization Administrator'), ('observer', 'Observer'), ('tester', 'Tester')], default='observer', help_text="User's role in the organization", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.User.profile_image_path),
        ),
    ]
