# Generated by Django 5.2.6 on 2025-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_automated',
        ),
        migrations.AlterField(
            model_name='user',
            name='auto_frequency',
            field=models.CharField(choices=[('n', 'None'), ('m', 'Monthly'), ('q', 'Quarterly')], max_length=1),
        ),
    ]
