# Generated by Django 5.2.6 on 2026-03-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invitation_recipient_email_hash_user_email_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationQuestionnaire',
        ),
    ]
