# Generated by Django 5.2.6 on 2026-04-01 19:44

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_email_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='recipient_role',
            field=models.CharField(choices=[('org_admin', 'Org Admin'), ('observer', 'Observer'), ('tester', 'Tester')], default='observer', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='raw_findings_json',
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, help_text='Encrypted. Full JSON findings from the exe. Deleted after report generation.', null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='target_subnet',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted. The subnet that was scanned (e.g. 192.168.1.0/24).', null=True),
        ),
    ]
