# Generated by Django 5.2.6 on 2026-03-15 16:39

import datetime
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_approved_at_organization_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invited_by',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='role',
        ),
        migrations.AddField(
            model_name='invitation',
            name='recipient_email',
            field=encrypted_fields.fields.EncryptedEmailField(default='test@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='recipient_role',
            field=models.CharField(choices=[('org_admin', 'Org Admin'), ('observer', 'Observer'), ('tester', 'Tester')], default='tester', max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email_domain',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='external_ip',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_domain',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 15, 16, 41, 11, 391515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(max_length=50),
        ),
    ]
