# Generated by Django 5.2.6 on 2026-02-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_organization_email_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='require_mfa_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employee_acceptable_use_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='require_mfa_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='require_mfa_sensitive_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='training_new_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='training_once_per_year',
            field=models.BooleanField(default=False),
        ),
    ]
