# Generated by Django 5.2.6 on 2026-04-11 17:41

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invitation_recipient_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, db_column='profile_image', null=True, upload_to=api.models.User.profile_image_path),
        ),
    ]
