# Generated by Django 5.2.6 on 2026-03-16 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_invited_by_invitation_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 2, 44, 13, 712582, tzinfo=datetime.timezone.utc)),
        ),
    ]
