# Generated by Django 5.2.6 on 2026-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_risk_resolved_at_risk_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_rotate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
