# Generated by Django 5.2.6 on 2026-04-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_organization_admin_rotate'),
        ('api', '0006_scan_scan_progress'),
    ]

    operations = [
    ]
