# Generated by Django 5.2.6 on 2026-03-16 02:52

import datetime
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_increase_password_length_to_128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 2, 57, 47, 967491, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=encrypted_fields.fields.EncryptedCharField(max_length=128),
        ),
    ]
