# Generated by Django 5.2.6 on 2026-03-16 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_otpverification_expires_at_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 15, 46, 51, 616242, tzinfo=datetime.timezone.utc)),
        ),
    ]
