# Generated by Django 5.2.6 on 2026-03-16 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 16, 21, 16, 76824, tzinfo=datetime.timezone.utc)),
        ),
    ]
