# Generated by Django 5.2.6 on 2026-03-17 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationquestionnaire',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 17, 16, 7, 58, 120237, tzinfo=datetime.timezone.utc)),
        ),
    ]
