# Generated by Django 5.2.6 on 2026-03-18 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_organizationquestionnaire_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 18, 19, 34, 41, 269377, tzinfo=datetime.timezone.utc)),
        ),
    ]
