# Generated by Django 5.2.6 on 2026-03-21 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 16, 7, 1, 452614, tzinfo=datetime.timezone.utc)),
        ),
    ]
