# Generated by Django 5.2.6 on 2026-03-21 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 17, 51, 30, 668190, tzinfo=datetime.timezone.utc)),
        ),
    ]
