# Generated by Django 5.2.6 on 2026-03-24 21:48

import api.models
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 24, 21, 53, 9, 131803, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ScanToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_tokens', to='api.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Token',
                'verbose_name_plural': 'Scan Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('RECEIVED', 'Results Received'), ('GENERATING', 'Generating Report'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('report_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('target_subnet', api.models.FernetEncryptedTextField(blank=True, help_text='Encrypted. The subnet that was scanned (e.g. 192.168.1.0/24).', null=True)),
                ('scanner_version', models.CharField(blank=True, max_length=20, null=True)),
                ('groups_completed', models.PositiveSmallIntegerField(default=0)),
                ('skipped_tools', models.JSONField(blank=True, default=list)),
                ('raw_findings_json', api.models.FernetEncryptedTextField(blank=True, help_text='Encrypted. Full JSON findings from the exe. Deleted after report generation.', null=True)),
                ('finding_count_critical', models.PositiveSmallIntegerField(default=0)),
                ('finding_count_high', models.PositiveSmallIntegerField(default=0)),
                ('finding_count_medium', models.PositiveSmallIntegerField(default=0)),
                ('finding_count_low', models.PositiveSmallIntegerField(default=0)),
                ('finding_count_info', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.organization')),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan', to='api.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan', to='api.scantoken')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
