# Generated by Django 5.2.6 on 2026-03-26 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_otpverification_expires_at_scantoken_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 26, 0, 44, 17, 978453, tzinfo=datetime.timezone.utc)),
        ),
    ]
