# Generated by Django 5.2.6 on 2026-03-27 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 1, 14, 32, 28175, tzinfo=datetime.timezone.utc)),
        ),
    ]
