# Generated by Django 5.2.6 on 2026-02-26 15:47

from django.db import migrations

def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Create the Groups
    admin_group, _ = Group.objects.get_or_create(name='Organization Admin')
    observer_group, _ = Group.objects.get_or_create(name='Observer')
    tester_group, _ = Group.objects.get_or_create(name='Tester')

    # Define the permission codenames for each group
    # Note: Django automatically creates view_, add_, change_, delete_ permissions for every model.
    # We omit 'can_view_any_report' and 'can_view_all_risk' to maintain organization isolation.
    
    observer_perms = [
        'view_report', 
        'view_risk',
    ]
    
    tester_perms = [
        'view_report',
        'view_risk',
        'can_resolve_risk', # Added the missing comma here!
    ]

    admin_perms = [
        'can_invite',
        'can_edit_permissions',
        'can_generate_report',
        'can_generate_risk',
        'view_report',
        'view_risk',
    ]

    # Helper function to assign permissions to a group
    def assign_permissions(group, codenames):
        for codename in codenames:
            try:
                # Fetch the permission object from the database
                perm = Permission.objects.get(codename=codename)
                group.permissions.add(perm)
            except Permission.DoesNotExist:
                print(f"Warning: Permission '{codename}' not found.")

    # Apply the permissions
    assign_permissions(observer_group, observer_perms)
    assign_permissions(tester_group, tester_perms)
    assign_permissions(admin_group, admin_perms)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_otpverification_expires_at'), 
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]